fineract:
  api:
    url: https://localhost/fineract-provider/api/v1
    tenant: default
    username: mifos
    password: password
    # Configurable locale and date format
    locale: en
    dateFormat: dd MMMM yyyy

keycloak:
  url: http://localhost:9000/realms/fineract/protocol/openid-connect/token
  grant-type: password
  client-id: community-app
  client-secret: "**********"

# RestTemplate configuration
rest:
  connection:
    timeout: 30000  # Connection timeout in milliseconds (30 seconds)
  read:
    timeout: 60000  # Read timeout in milliseconds (60 seconds)

# Retry configuration
retry:
  max-attempts: 3
  initial-interval: 1000  # Initial backoff interval in milliseconds
  multiplier: 2.0  # Backoff multiplier
  max-interval: 10000  # Maximum backoff interval in milliseconds
